### PR TITLE
fix libusb error Entity not found under macos

### PR DESCRIPTION
**Pull request by Frederick888**
There have been a few related issues at libusb/libusb#158 libusb/libusb#214.

I haven't got time to deep dive into details but with the attach/detach/claim/release calls under macOS, I got either `Entity not found` or permission denied. Without these calls everything works fine and there's no problem like #4 under Linux.

### CODE REVIEW

**Comment by Frederick888** [comment]
@wisespace-io Sorry for being pushy but is it possible for you merge this and publish a new version? I'd like to have this fix in my downstream project :)

**Comment by wisespace-io** [comment]
@Frederick888 I do not how I did not notice your Pull Request before.
Merging now, thank you for fixing it.

**Comment by wisespace-io** [comment]
@Frederick888 Your fix was included in version 0.6.4

I fixed some warnings and bumped some dependencies and release under 0.7.0.

**Comment by Frederick888** [comment]
Cool! Thanks a ton!

**Pull request merged**
